build-job:
  variables:
    DEVENV_REPO: devworldsony/spresense-sdk-env:latest
  stage: build
  tags:
    - tvk-home
  script:
    - docker pull $DEVENV_REPO
    - shopt -s expand_aliases
    - id
    - alias spresense='docker run --rm -i -u `id -u`:`id -g`  -v '"`pwd`:/spresense -w /spresense/sdk $DEVENV_REPO"
    - type spresense
    - spresense ls
    - spresense tools/config.py examples/hello
    



