build-job:
  stage: build
  tags:
    - tvk-home
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - bash source spresense_env.sh
    - spresense tools/config.py examples/hello
    - spresense make

test-job1:
  stage: test
  tags:
    - tvk-home
  script:
    - echo "This job tests something"

test-job2:
  stage: test
  tags:
    - tvk-home
  script:
    - echo "This job tests something, but takes more time than test-job1."
    - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
    - echo "which simulates a test that runs 20 seconds longer than test-job1"
    - sleep 20

deploy-prod:
  stage: deploy
  tags:
    - tvk-home
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."

