build-job:
  variables:
    DEVENV_REPO: devworldsony/spresense-sdk-env:latest
  stage: build
  tags:
    - tvk-home
  script:
    - docker pull $DEVENV_REPO
    - pwd
    - docker run --rm -it -u `id -u`:`id -g` ls


