build-job:
  variables:
    DEVENV_REPO: devworldsony/spresense-sdk-env:latest
  stage: build
  tags:
    - tvk-home
  script:
    - docker pull $DEVENV_REPO
    - docker run --rm -it -u `id -u`:`id -g`  -v "`pwd`:/spresense -w /spresense/sdk $DEVENV_REPO" tools/config.py examples/hello
    - ls



