build-job:
  variables:
    DEVENV_REPO: devworldsony/spresense-sdk-env:latest
    GIT_SUBMODULE_STRATEGY: recursive
  stage: build
  tags:
    - tvk-home
  script:
    - docker pull $DEVENV_REPO
    - shopt -s expand_aliases
    - id
    - alias spresense='docker run --rm -i -u `id -u`:`id -g`  -v '"`pwd`:/spresense -w /spresense/sdk $DEVENV_REPO"
    - type spresense
    - spresense tools/config.py examples/hello
    - spresense tools/flash.sh -e /spresense/firmware/spresense/spresense-binaries-v2.4.0.zip
    - spresense tools/config.py examples/hello
    - spresense make
    

